#!/usr/bin/zsh
#
#  Author: peek4bUh
#  Filename: bspwm/bspwmrc
#  Repository: https://github.com/peek4bUh/dotfiles
#  Source: https://github.com/baskerville/bspwm
#


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     

bspc config border_width 2
bspc config window_gap 4
bspc config split_ratio 0.50

bspc rule -a 'Spotify:*' desktop="^5"

# Remove default "X" cursor from root window
# see https://www.reddit.com/r/bspwm/comments/s5xsph/cursor_problem
xsetroot -cursor_name left_ptr
